const SPREADSHEET_ID='1sxMGwQEDC3-vKddo2rQeMT3aNExVZ1U091fybJTQptQ',TZ='Europe/Rome';
function doGet(){return out_({ok:true,service:'CRM Reclutamento',version:'2.0'})}
function doPost(e){const lock=LockService.getScriptLock();lock.waitLock(15000);try{const d=e.parameter||{};return out_({ok:true,result:route_(d)})}catch(x){return out_({ok:false,error:String(x.message||x)})}finally{lock.releaseLock()}}
function out_(v){return ContentService.createTextOutput(JSON.stringify(v)).setMimeType(ContentService.MimeType.JSON)}
function route_(d){if(d.action==='login')return login_(d);const s=session_(d.token);if(d.action==='dashboard')return dashboard_(s);if(d.action==='contact')return contact_(d.leadId,s);if(d.action==='answer')return answer_(d,s);if(d.action==='event')return event_(d,s);if(d.action==='nextStep')return next_(d,s);throw Error('Azione non riconosciuta')}

function login_(d){const p=PropertiesService.getScriptProperties(),level=String(d.level||'operator'),user=String(d.username||'').trim().toLowerCase(),hash=sha_(String(d.password||''));let valid=false,operator='';if(level==='admin')valid=equal_(hash,p.getProperty('ADMIN_PASSWORD_HASH')||'');else{valid=user===String(p.getProperty('STEFANO_USERNAME')||'').toLowerCase()&&equal_(hash,p.getProperty('STEFANO_PASSWORD_HASH')||'');operator='Stefano'}if(!valid)throw Error('User o password non corretti');const token=Utilities.getUuid()+Utilities.getUuid();CacheService.getScriptCache().put('session:'+token,JSON.stringify({level:level,operator:operator}),21600);return{token:token,level:level,operator:operator}}
function session_(token){const raw=CacheService.getScriptCache().get('session:'+String(token||''));if(!raw)throw Error('Sessione scaduta: accedi di nuovo');return JSON.parse(raw)}

function dashboard_(session){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),rows=objects_(ss.getSheetByName('CONTATTI'));const mine=rows.filter(r=>{const op=pick_(r,['OPERATORE','REFERENTE','ASSEGNATO A']);return!op||norm_(op)===norm_(session.operator||'Stefano')});let latest=null;mine.forEach(r=>{const d=date_(pick_(r,['DATA BOOTCAMP','BOOTCAMP','DATA DEL BOOTCAMP']));if(d&&(!latest||d>latest))latest=d});const contacts=mine.filter(r=>{if(!latest)return true;const d=date_(pick_(r,['DATA BOOTCAMP','BOOTCAMP','DATA DEL BOOTCAMP']));return d&&day_(d)===day_(latest)}).map(dto_);contacts.sort((a,b)=>a.status!==b.status?(a.status==='Da lavorare'?-1:1):(b.sortDate-a.sortDate));return{bootcampLabel:latest?'Bootcamp '+Utilities.formatDate(latest,TZ,'d MMMM yyyy'):'Ultimo Bootcamp',contacts:contacts,appointments:steps_(ss,session.operator||'Stefano')}}
function contact_(id,session){const lead=find_(id),vals=lead.sheet.getRange(lead.row,1,1,lead.sheet.getLastColumn()).getValues()[0],heads=lead.sheet.getRange(1,1,1,lead.sheet.getLastColumn()).getDisplayValues()[0],answers={};heads.forEach((h,i)=>answers[norm_(h)]=vals[i]);const events=objects_(SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName('EVENTI')).filter(r=>String(pick_(r,['ID CONTATTO','LEAD ID','CONTATTO ID']))===String(id)).sort((a,b)=>date_(pick_(b,['DATA/ORA','DATA ORA','DATA']))-date_(pick_(a,['DATA/ORA','DATA ORA','DATA']))).map(r=>({type:pick_(r,['TIPO EVENTO','EVENTO','TIPO']),detail:pick_(r,['DETTAGLIO','NOTE','NOTA']),operator:pick_(r,['OPERATORE','REFERENTE'])||session.operator,whenLabel:format_(pick_(r,['DATA/ORA','DATA ORA','DATA']))}));return{answers:answers,events:events}}

function answer_(d,s){required_(d);const lead=find_(d.leadId),map=headers_(lead.sheet),field=norm_(d.field);if(!map[field])throw Error('Campo non presente nel database: '+d.field);lead.sheet.getRange(lead.row,map[field]).setValue(d.value||'');set_(lead,map,'ULTIMO AGGIORNAMENTO',new Date());append_(d.leadId,'Risposta aggiornata',d.field,d.value||'','','',s.operator);SpreadsheetApp.flush();return{saved:true}}
function event_(d,s){required_(d);append_(d.leadId,d.eventType||'Evento',d.detail||'',d.note||'','',d.newStatus||'Lavorato',s.operator);const lead=find_(d.leadId),map=headers_(lead.sheet);set_(lead,map,'STATO',d.newStatus||'Lavorato');set_(lead,map,'ULTIMO AGGIORNAMENTO',new Date());SpreadsheetApp.flush();return{saved:true}}
function next_(d,s){required_(d);const ss=SpreadsheetApp.openById(SPREADSHEET_ID),lead=find_(d.leadId),map=headers_(lead.sheet),when=d.when?new Date(d.when):'',name=cell_(lead,map,['NOME E COGNOME','NOME COMPLETO','CONTATTO','NOME']),phone=cell_(lead,map,['TELEFONO','CELLULARE','PHONE']);let cal='';if(String(d.createCalendar)==='true'&&when){const ev=CalendarApp.getDefaultCalendar().createEvent((d.stepType||'Richiamo')+' – '+(name||d.leadId),when,new Date(when.getTime()+1800000),{description:(d.note||'')+'\nTelefono: '+phone+'\nContatto CRM: '+d.leadId+'\n'+(d.crmLink||'')});cal=ev.getId()}set_(lead,map,'STATO','Lavorato');set_(lead,map,'PROSSIMO STEP',d.stepType||'');set_(lead,map,'DATA/ORA PROSSIMO STEP',when);set_(lead,map,'CREA EVENTO CALENDAR',String(d.createCalendar)==='true'?'Sì':'No');set_(lead,map,'ID EVENTO GOOGLE',cal);set_(lead,map,'ULTIMO AGGIORNAMENTO',new Date());ss.getSheetByName('PROSSIMI_STEP').appendRow([Utilities.getUuid(),d.leadId,name,d.stepType||'',when,'Da fare','',String(d.createCalendar)==='true'?'Sì':'No',cal,d.crmLink||'',d.note||'',s.operator||'Stefano']);append_(d.leadId,'Prossimo step impostato',d.stepType||'',d.note||'','','Lavorato',s.operator);SpreadsheetApp.flush();return{saved:true,calendarId:cal}}

function steps_(ss,operator){const sh=ss.getSheetByName('PROSSIMI_STEP');if(!sh||sh.getLastRow()<2)return[];const now=new Date();return objects_(sh).filter(r=>{const d=date_(pick_(r,['DATA/ORA','DATA/ORA PROSSIMO STEP','DATA ORA'])),op=pick_(r,['OPERATORE','REFERENTE']),st=norm_(pick_(r,['STATO']));return d&&d>=now&&(!op||norm_(op)===norm_(operator))&&st!=='COMPLETATO'}).sort((a,b)=>date_(pick_(a,['DATA/ORA','DATA/ORA PROSSIMO STEP','DATA ORA']))-date_(pick_(b,['DATA/ORA','DATA/ORA PROSSIMO STEP','DATA ORA']))).slice(0,9).map(r=>({leadId:pick_(r,['ID CONTATTO','LEAD ID']),name:pick_(r,['NOME E COGNOME','CONTATTO','NOME']),type:pick_(r,['TIPO','AZIONE','PROSSIMO STEP']),note:pick_(r,['NOTE','NOTA']),whenLabel:format_(pick_(r,['DATA/ORA','DATA/ORA PROSSIMO STEP','DATA ORA']))}))}
function dto_(r){const raw=norm_(pick_(r,['STATO','STATO LAVORAZIONE'])),updated=date_(pick_(r,['ULTIMO AGGIORNAMENTO','DATA IMPORTAZIONE','DATA REGISTRAZIONE','TIMESTAMP']));return{id:pick_(r,['ID CONTATTO','LEAD ID','ID']),name:pick_(r,['NOME E COGNOME','NOME COMPLETO','CONTATTO','NOME']),phone:pick_(r,['TELEFONO','CELLULARE','PHONE']),region:pick_(r,['REGIONE','PROVINCIA','CITTÀ','CITTA']),status:raw&&raw!=='DA LAVORARE'?'Lavorato':'Da lavorare',dateLabel:format_(pick_(r,['DATA IMPORTAZIONE','DATA REGISTRAZIONE','TIMESTAMP'])),bootcampLabel:'Bootcamp '+format_(pick_(r,['DATA BOOTCAMP','BOOTCAMP','DATA DEL BOOTCAMP'])),sortDate:updated?updated.getTime():0}}
function append_(id,type,detail,note,oldStatus,newStatus,operator){SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName('EVENTI').appendRow([Utilities.getUuid(),id,new Date(),operator||'Stefano',type,detail||'',note||'',oldStatus||'',newStatus||'','WEBAPP'])}

function find_(id){const sh=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName('CONTATTI'),hit=sh.getRange(1,1,sh.getMaxRows(),1).createTextFinder(String(id)).matchEntireCell(true).findNext();if(!hit)throw Error('Contatto non trovato: '+id);return{sheet:sh,row:hit.getRow()}}
function objects_(sh){if(!sh||sh.getLastRow()<2)return[];const v=sh.getDataRange().getValues(),h=v.shift().map(norm_);return v.map(row=>{const o={};h.forEach((x,i)=>o[x]=row[i]);return o})}
function headers_(sh){const h=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],m={};h.forEach((x,i)=>m[norm_(x)]=i+1);return m}
function pick_(o,n){for(let i=0;i<n.length;i++){const v=o[norm_(n[i])];if(v!==''&&v!=null)return v}return''}
function cell_(lead,map,n){for(let i=0;i<n.length;i++){const c=map[norm_(n[i])];if(c)return lead.sheet.getRange(lead.row,c).getDisplayValue()}return''}
function set_(lead,map,n,v){const c=map[norm_(n)];if(c)lead.sheet.getRange(lead.row,c).setValue(v)}
function norm_(v){return String(v==null?'':v).trim().toUpperCase()}
function date_(v){if(v instanceof Date&&!isNaN(v))return v;const d=new Date(v);return isNaN(d)?null:d}
function day_(d){return Utilities.formatDate(d,TZ,'yyyyMMdd')}
function format_(v){const d=date_(v);return d?Utilities.formatDate(d,TZ,'dd/MM/yyyy HH:mm'):String(v||'')}
function required_(d){if(!d.leadId)throw Error('Contatto non indicato')}
function sha_(v){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,v).map(b=>('0'+(b&255).toString(16)).slice(-2)).join('')}
function equal_(a,b){if(!a||!b||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}

// Inserire le password, eseguire una volta e poi cancellare i valori prima di pubblicare il codice.
function configuraAccessi(){const USER_STEFANO='stefano',PASSWORD_STEFANO='INSERISCI_PASSWORD_STEFANO',PASSWORD_ADMIN='INSERISCI_PASSWORD_ADMIN';if(PASSWORD_STEFANO.indexOf('INSERISCI_')===0||PASSWORD_ADMIN.indexOf('INSERISCI_')===0)throw Error('Inserisci prima le due password');PropertiesService.getScriptProperties().setProperties({STEFANO_USERNAME:USER_STEFANO,STEFANO_PASSWORD_HASH:sha_(PASSWORD_STEFANO),ADMIN_PASSWORD_HASH:sha_(PASSWORD_ADMIN)})}
